spring.profiles.active=local
#spring.profiles.active=test
#spring.profiles.active=operation


spring.config.import=optional:file:./backend/src/main/resources/config/.env.local[.properties]
#spring.config.import=optional:file:./backend/src/main/resources/config/.env.test[.properties]
#spring.config.import=optional:file:./backend/src/main/resources/config/.env.operation[.properties]

